version: '3.8'

services:
  voiturerc:
    image: theorywrong/rctelemetrie
    container_name: telemetrie
    restart: always
    devices:
      - /dev/gpiomem
      - /dev/vchiq
  ustreamer:
    image: theorywrong/ustreamer:latest
    container_name: ustreamer
    restart: always
    privileged: true
    command: -d /dev/video0 -Z --host 192.168.1.15 --port 1337 -f 25 -c M2M-IMAGE
    devices:
      - /dev/video0
